"""
report_generator.py  (place this in src/)
──────────────────────────────────────────
Generates a PDF risk report for a student using fpdf2.

Usage:
    from report_generator import generate_pdf_report
    path = generate_pdf_report("Arpita", "High", 74.2, tips, shap_dict)
"""

import os
import datetime
from fpdf import FPDF

CLASS_NAMES = ['Low', 'Moderate', 'High', 'Severe']


class ReportPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 13)
        self.set_fill_color(30, 90, 160)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, '  E-Gadget Addiction Risk Report', ln=True, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def footer(self):
        self.set_y(-14)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f'KLE College of Engineering · Confidential · '
                         f'Page {self.page_no()}', align='C')


def generate_pdf_report(
    student_name : str,
    risk_label   : str,
    score        : float,
    tips         : list,
    shap_impact  : dict  = None,
    waterfall_img: str   = None,
    save_dir     : str   = None,
) -> str:
    """
    Parameters
    ----------
    student_name  : display name
    risk_label    : 'Low' | 'Moderate' | 'High' | 'Severe'
    score         : Addiction Risk Score 0-100
    tips          : list of recommendation strings
    shap_impact   : {feature: shap_value} dict (optional)
    waterfall_img : path to SHAP waterfall PNG (optional)
    save_dir      : directory to save PDF (default: reports/)

    Returns
    -------
    pdf_path : str
    """
    if save_dir is None:
        save_dir = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), '..', 'reports'
        )
    os.makedirs(save_dir, exist_ok=True)

    pdf = ReportPDF()
    pdf.add_page()

    # ── Student info block ────────────────────────────────────────────
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, f'Student : {student_name or "Anonymous"}', ln=True)
    pdf.cell(0, 8, f'Date    : {datetime.date.today().strftime("%B %d, %Y")}', ln=True)
    pdf.ln(3)

    # ── Risk badge ────────────────────────────────────────────────────
    color_map = {
        'Low'     : (39,  174,  96),
        'Moderate': (243, 156,  18),
        'High'    : (230, 126,  34),
        'Severe'  : (192,  57,  43),
    }
    r, g, b = color_map.get(risk_label, (0, 0, 0))
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(60, 12, f'  Risk Level: {risk_label}', fill=True, ln=False)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Helvetica', '', 12)
    pdf.cell(0, 12, f'   Addiction Risk Score: {score} / 100', ln=True)
    pdf.ln(4)

    # ── SHAP feature impacts ──────────────────────────────────────────
    if shap_impact:
        pdf.set_font('Helvetica', 'B', 11)
        pdf.cell(0, 8, 'Key Contributing Factors (SHAP):', ln=True)
        pdf.set_font('Helvetica', '', 10)
        for feat, val in list(shap_impact.items())[:6]:
            arrow = 'increases' if val > 0 else 'decreases'
            pdf.cell(0, 7, f'  • {feat}: {val:+.3f}  ({arrow} risk)', ln=True)
        pdf.ln(2)

    # ── Waterfall image ───────────────────────────────────────────────
    if waterfall_img and os.path.isfile(waterfall_img):
        pdf.set_font('Helvetica', 'B', 11)
        pdf.cell(0, 8, 'SHAP Explanation Chart:', ln=True)
        pdf.image(waterfall_img, x=10, w=185)
        pdf.ln(4)

    # ── Recommendations ───────────────────────────────────────────────
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, 'Personalised Recommendations:', ln=True)
    pdf.set_font('Helvetica', '', 10)
    for tip in tips:
        # strip emoji for PDF (basic latin only)
        safe_tip = tip.encode('latin-1', errors='replace').decode('latin-1')
        pdf.multi_cell(0, 7, f'  {safe_tip}')
    pdf.ln(3)

    # ── Disclaimer ────────────────────────────────────────────────────
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 6,
        'This report is generated by an AI-based prediction system and is intended '
        'as a supportive tool only. It does not constitute medical or psychological '
        'advice. Please consult a qualified professional for clinical assessment.')

    safe_name = (student_name or 'student').replace(' ', '_')
    filename  = f"{safe_name}_{datetime.date.today()}_report.pdf"
    pdf_path  = os.path.join(save_dir, filename)
    pdf.output(pdf_path)
    print(f"[report] PDF saved → {pdf_path}")
    return pdf_path


if __name__ == '__main__':
    sample_tips = [
        "Set daily screen time limits.",
        "Sleep by 10 PM.",
        "Increase physical activity.",
    ]
    generate_pdf_report(
        student_name = "Demo Student",
        risk_label   = "High",
        score        = 72.5,
        tips         = sample_tips,
    )
